// Splitting generated files. A generated file that would pass the line limit becomes a directory of
// the same name, split by area (BLD-SRC for builds and sources, which have no area), then by kind,
// then by a block of 100 numbers, or by the first character of a build's or source's alias.

import type { Context } from "../context.ts";
import { areaOf, kindOf } from "../ids.ts";
import { lineCount } from "../markdown.ts";
import { KINDS, LINE_LIMIT } from "../standard.ts";
import type { Render } from "../types.ts";

const groupOf = (id: string) => (["BLD", "SRC"].includes(kindOf(id)) ? "BLD-SRC" : areaOf(id));
/** The block of an ID in a split file: its hundred, such as 100, or the first character of an alias. */
export const blockOf = (id: string) => {
  const kind = kindOf(id);
  if (kind === "BLD" || kind === "SRC") return id.charAt(kind.length + 1);
  return String(Math.floor(Number(id.split("-")[2]) / 100) * 100).padStart(3, "0");
};
const SPLIT_LEVELS = [groupOf, kindOf, blockOf];
function orderKeys(areas: string[], level: number, keys: string[]) {
  if (level === 0) return [...areas.filter((a) => keys.includes(a)), ...keys.filter((k) => !areas.includes(k)).sort()];
  if (level === 1) return Object.keys(KINDS).filter((k) => keys.includes(k));
  return keys.sort((a, b) => (/^\d+$/.test(a) && /^\d+$/.test(b) ? Number(a) - Number(b) : a < b ? -1 : a > b ? 1 : 0));
}
/**
 * Lays out one generated file: `${name}.md` when render's text fits, otherwise a directory split only
 * as far as the limit requires. render(ids, path) gives the text of the file at path, which has no
 * .md and is relative to the generated tree. Returns a Map of path -> { ids, text }.
 */
export function layout(
  ctx: Context,
  name: string,
  ids: string[],
  render: Render,
  level = 0,
  out = new Map<string, { ids: string[]; text: string }>(),
) {
  const text = render(ids, name);
  const { problem } = ctx;
  if (lineCount(text) <= LINE_LIMIT || level === SPLIT_LEVELS.length) {
    if (lineCount(text) > LINE_LIMIT) problem(null, `${name}.md would pass ${LINE_LIMIT} lines even split by block`);
    out.set(name, { ids, text });
    return out;
  }
  const groups = new Map<string, string[]>();
  for (const id of ids) {
    const key = SPLIT_LEVELS[level]!(id);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(id);
  }
  for (const key of orderKeys(ctx.spec.areas, level, [...groups.keys()]))
    layout(ctx, `${name}/${key}`, groups.get(key)!, render, level + 1, out);
  return out;
}
/** The comment every generated file carries under its heading. */
export const GENERATED = "<!-- Generated by the documentation standard check. Do not edit. -->";
